on:
  push:
    branches: 
      - jdc

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          cd /opt/rt-n56u/trunk
          wget https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/jdc.config -O configs/templates/JDC.config

          # remove the dnsmasq cache size config
          sed -i 's/fprintf(fp, "cache-size=%d\\n", DNS_RELAY_CACHE_MAX);/\/\/fprintf(fp, "cache-size=%d\\n", DNS_RELAY_CACHE_MAX);/' user/rc/services_ex.c
          # sed -i 's/DNS_RELAY_CACHE_MAX\t\t1024/DNS_RELAY_CACHE_MAX\t\t10000/' user/rc/rc.h

          # enlarge the storage size
          # sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x80000/CONFIG_MTD_STORE_PART_SIZ=0x600000/' configs/boards/JDC/kernel-3.4.x.config
          # sed -i 's/mtd_part_size=65536/mtd_part_size=6291456/' user/scripts/mtd_storage.sh

          # build-in smartdns
          mkdir -p user/smartdns
          wget -P user/smartdns/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/smartdns/Makefile
          wget https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/user/Makefile -O user/Makefile
          sed -i '$a\export SSL_CERT_FILE=/usr/lib/cacert.pem' user/scripts/profile

          # xray
          mkdir -p user/xray
          wget -P user/xray/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/xray/Makefile
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_V2RAY=y/CONFIG_FIRMWARE_INCLUDE_V2RAY=n/' configs/templates/JDC.config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_XRAY=n/CONFIG_FIRMWARE_INCLUDE_XRAY=y/' configs/templates/JDC.config
          fakeroot ./build_firmware_modify JDC
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/jdc_xray.trx
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: /opt/bin
